on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ZAP baseline scan
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          ZAP_FILE_NAME: 'zap.yaml'
          WORKING_BRANCH: 'master'
          DOCKER_FILE: 'sshniro/zap_action:latest'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
